name: 'Setup dfx environment with dfxvm'
author: 'Quint Daenen, modified by Byron Becker'
description: 'Setup a dfx environment and add it to the PATH.'
inputs:
  dfx-version:
    description: 'The dfx version to download.'
  dfx-disable-encryption:
    description: 'Wether to use the .pem encryption'
    default: "false"
  install-moc:
    description: 'Whether to install moc through dfx.'
    default: "false"
  vessel-version:
    description: 'The vessel version to download.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'gray-dark'
