name: 'Setup vessel environment'
author: 'Quint Daenen, modified by Byron Becker'
description: 'Setup a vessel environment and add it to the PATH.'
inputs:
  vessel-version:
    description: 'The vessel version to download.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'gray-dark'
