on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          dfx-version: 0.7.2
          vessel-version: 0.6.2
      - run: |
          dfx --version
          moc --version
          vessel --version
